// Code generated by "goki version"; DO NOT EDIT.

package kid

const (
	// Version is the version of this package being used
	Version = "v0.0.2"
	// GitCommit is the commit just before the latest version commit
	GitCommit = "ea7aed1"
	// VersionDate is the date-time of the latest version commit in UTC (in the format 'YYYY-MM-DD HH:MM', which is the Go format '2006-01-02 15:04')
	VersionDate = "2023-12-02 01:29"
)
